# OAuth 2.0 Setup Guide

> **Official docs**: https://developers.google.com/identity/protocols/oauth2

This document covers the complete OAuth 2.0 setup process for Gmail API access, from Google Cloud Console configuration through token generation.

## Credential Storage

All credentials are stored in `~/.gmail-skill/`:

| File | Purpose | Source |
|------|---------|--------|
| `client_secret.json` | OAuth client credentials | Downloaded from Google Cloud Console |
| `tokens.json` | Access and refresh tokens | Generated by authorization flow |

```bash
# Verify credential directory
ls -la ~/.gmail-skill/
```

---

## Step 1: Create Google Cloud Project {#create-project}

1. Go to [Google Cloud Console](https://console.cloud.google.com/)
2. Click the project dropdown (top-left, next to "Google Cloud")
3. Click **New Project**
4. Enter project details:
   - **Project name**: Choose a descriptive name (e.g., "Gmail Skill")
   - **Organization**: Leave as default or select your organization
5. Click **Create**
6. Wait for project creation (notification will appear)
7. Select the new project from the dropdown

---

## Step 2: Enable Gmail API {#enable-api}

1. In your project, go to **APIs & Services** > **Library**
2. Search for "Gmail API"
3. Click **Gmail API** in results
4. Click **Enable**
5. Wait for API to enable (redirects to API overview page)

### Verify API is Enabled

1. Go to **APIs & Services** > **Enabled APIs & services**
2. Confirm "Gmail API" appears in the list

---

## Step 3: Configure OAuth Consent Screen {#consent-screen}

Before creating credentials, you must configure the OAuth consent screen.

1. Go to **APIs & Services** > **OAuth consent screen**
2. Select **User Type**:
   - **External**: For any Google account (recommended for personal use)
   - **Internal**: Only for Google Workspace organization members
3. Click **Create**

### App Information

| Field | Value |
|-------|-------|
| App name | Your app name (e.g., "Gmail Skill") |
| User support email | Your email address |
| App logo | Optional |

### App Domain (Optional)

Leave blank for local/CLI applications.

### Developer Contact Information

| Field | Value |
|-------|-------|
| Email addresses | Your email address |

Click **Save and Continue**.

### Scopes Configuration

1. Click **Add or Remove Scopes**
2. Search for and select the scopes you need:

| Scope | Description | Use When |
|-------|-------------|----------|
| `https://www.googleapis.com/auth/gmail.readonly` | Read emails and labels | Read-only access |
| `https://www.googleapis.com/auth/gmail.compose` | Create and manage drafts | Draft operations |
| `https://www.googleapis.com/auth/gmail.send` | Send emails | Sending only |
| `https://www.googleapis.com/auth/gmail.modify` | Full read/write/delete | Most operations |
| `https://www.googleapis.com/auth/gmail.labels` | Manage labels only | Label management |
| `https://www.googleapis.com/auth/gmail.settings.basic` | Basic account settings | Vacation responder, forwarding |

**Recommendation**: Start with `gmail.modify` for full functionality.

3. Click **Update**
4. Click **Save and Continue**

### Test Users (External Apps Only)

If you selected "External" user type, your app is in "Testing" mode:

1. Click **Add Users**
2. Enter email addresses of accounts that will use the app
3. Click **Add**
4. Click **Save and Continue**

**Important**: Testing apps have these limitations:
- Maximum 100 test users
- Refresh tokens expire in 7 days
- Only test users can authorize the app

### Publishing Status

| Status | Behavior |
|--------|----------|
| **Testing** | Only test users can authorize; tokens expire in 7 days |
| **In production** | Any Google account can authorize; tokens last indefinitely |

To move to production:
1. Go to **OAuth consent screen**
2. Click **Publish App**
3. Complete Google's verification process (may require privacy policy, etc.)

---

## Step 4: Create OAuth Client Credentials {#create-credentials}

1. Go to **APIs & Services** > **Credentials**
2. Click **+ Create Credentials**
3. Select **OAuth client ID**
4. Choose **Application type**: **Desktop app**
5. Enter a name (e.g., "Gmail Skill CLI")
6. Click **Create**

### Download and Store Credentials

1. After creation, a dialog shows your client ID and secret
2. Click **Download JSON**
3. Rename the file to `client_secret.json`
4. Move to credential directory:

```bash
mkdir -p ~/.gmail-skill
mv ~/Downloads/client_secret*.json ~/.gmail-skill/client_secret.json
chmod 600 ~/.gmail-skill/client_secret.json
```

### Credential File Structure

The `client_secret.json` file has this structure:

```json
{
  "installed": {
    "client_id": "123456789-abc123.apps.googleusercontent.com",
    "project_id": "your-project-id",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_secret": "GOCSPX-your-secret-here",
    "redirect_uris": ["http://localhost"]
  }
}
```

---

## Step 5: First-Time Authorization Flow {#authorize}

Run this script to generate an authorization URL and exchange the code for tokens:

```bash
tsx << 'EOF'
import { google } from "googleapis";
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { homedir } from "os";
import { join } from "path";
import { createInterface } from "readline";

const credPath = join(homedir(), ".gmail-skill");
const clientSecretPath = join(credPath, "client_secret.json");
const tokensPath = join(credPath, "tokens.json");

// Ensure directory exists
if (!existsSync(credPath)) {
  mkdirSync(credPath, { mode: 0o700 });
}

// Load client credentials
if (!existsSync(clientSecretPath)) {
  console.error("ERROR: client_secret.json not found at:", clientSecretPath);
  console.error("Download from Google Cloud Console and save to this location.");
  process.exit(1);
}

const credentials = JSON.parse(readFileSync(clientSecretPath, "utf8"));
const { client_id, client_secret, redirect_uris } = credentials.installed;

const oauth2Client = new google.auth.OAuth2(
  client_id,
  client_secret,
  redirect_uris[0]
);

// Define scopes - adjust based on your needs
const SCOPES = [
  "https://www.googleapis.com/auth/gmail.modify"  // Full access
  // Alternative scopes:
  // "https://www.googleapis.com/auth/gmail.readonly",  // Read only
  // "https://www.googleapis.com/auth/gmail.send",      // Send only
  // "https://www.googleapis.com/auth/gmail.compose",   // Drafts
];

// Generate authorization URL
const authUrl = oauth2Client.generateAuthUrl({
  access_type: "offline",  // Required for refresh token
  scope: SCOPES,
  prompt: "consent"        // Force consent to get refresh token
});

console.log(`
╔══════════════════════════════════════════════════════════════════╗
║                  GMAIL OAUTH 2.0 AUTHORIZATION                   ║
╠══════════════════════════════════════════════════════════════════╣
║  Step 1: Open this URL in your browser                           ║
╚══════════════════════════════════════════════════════════════════╝

${authUrl}

╔══════════════════════════════════════════════════════════════════╗
║  Step 2: Sign in and grant access to your Gmail account          ║
║  Step 3: Copy the authorization code from the redirect URL       ║
║                                                                  ║
║  The redirect URL will look like:                                ║
║  http://localhost/?code=4/0ABC...&scope=...                      ║
║                                                                  ║
║  Copy everything after "code=" and before "&scope"               ║
╚══════════════════════════════════════════════════════════════════╝
`);

// Read authorization code from stdin
const rl = createInterface({
  input: process.stdin,
  output: process.stdout
});

rl.question("Enter the authorization code: ", async (code) => {
  rl.close();

  try {
    // Exchange code for tokens
    const { tokens } = await oauth2Client.getToken(code.trim());

    // Save tokens
    writeFileSync(tokensPath, JSON.stringify(tokens, null, 2));
    console.log("\nTokens saved to:", tokensPath);

    // Verify by getting profile
    oauth2Client.setCredentials(tokens);
    const gmail = google.gmail({ version: "v1", auth: oauth2Client });
    const profile = await gmail.users.getProfile({ userId: "me" });

    console.log("\nAuthorization successful!");
    console.log("Email:", profile.data.emailAddress);
    console.log("Messages:", profile.data.messagesTotal);

  } catch (error: any) {
    console.error("\nAuthorization failed:", error.message);
    if (error.message.includes("invalid_grant")) {
      console.error("The authorization code may have expired. Try again.");
    }
    process.exit(1);
  }
});
EOF
```

### Token File Structure

After successful authorization, `tokens.json` contains:

```json
{
  "access_token": "ya29.a0AfH6SMB...",
  "refresh_token": "1//0eXyz...",
  "scope": "https://www.googleapis.com/auth/gmail.modify",
  "token_type": "Bearer",
  "expiry_date": 1699500000000
}
```

| Field | Description |
|-------|-------------|
| `access_token` | Short-lived token for API calls (~1 hour) |
| `refresh_token` | Long-lived token to get new access tokens |
| `expiry_date` | Unix timestamp when access token expires |
| `scope` | Authorized scopes |

---

## Token Refresh Behavior {#token-refresh}

The `googleapis` library handles token refresh automatically.

### Automatic Refresh

```bash
tsx << 'EOF'
import { google } from "googleapis";
import { readFileSync, writeFileSync } from "fs";
import { homedir } from "os";
import { join } from "path";

const credPath = join(homedir(), ".gmail-skill");
const credentials = JSON.parse(readFileSync(join(credPath, "client_secret.json"), "utf8"));
const tokens = JSON.parse(readFileSync(join(credPath, "tokens.json"), "utf8"));

const oauth2Client = new google.auth.OAuth2(
  credentials.installed.client_id,
  credentials.installed.client_secret,
  credentials.installed.redirect_uris[0]
);
oauth2Client.setCredentials(tokens);

// Listen for token refresh events and save new tokens
oauth2Client.on("tokens", (newTokens) => {
  console.log("Tokens refreshed, saving...");
  const updatedTokens = { ...tokens, ...newTokens };
  writeFileSync(join(credPath, "tokens.json"), JSON.stringify(updatedTokens, null, 2));
});

const gmail = google.gmail({ version: "v1", auth: oauth2Client });

// This call will auto-refresh if access token is expired
const profile = await gmail.users.getProfile({ userId: "me" });
console.log("Connected as:", profile.data.emailAddress);
EOF
```

### When Refresh Tokens Expire

Refresh tokens can become invalid in these situations:

| Condition | When It Happens | Solution |
|-----------|-----------------|----------|
| **Unused for 6 months** | No API calls for 6 months | Re-authorize |
| **Password change** | User changes Google password | Re-authorize |
| **Token limit exceeded** | >50 refresh tokens for same app/user | Re-authorize (oldest token revoked) |
| **User revokes access** | User removes app in Google settings | Re-authorize |
| **Testing app expiry** | App in "Testing" status, 7 days passed | Re-authorize or publish app |
| **Admin revocation** | Google Workspace admin revokes | Contact admin |

### Check Token Status

```bash
tsx << 'EOF'
import { readFileSync, existsSync } from "fs";
import { homedir } from "os";
import { join } from "path";

const tokensPath = join(homedir(), ".gmail-skill", "tokens.json");

if (!existsSync(tokensPath)) {
  console.log("Status: NOT_AUTHORIZED");
  console.log("Run the authorization flow to create tokens.");
  process.exit(0);
}

const tokens = JSON.parse(readFileSync(tokensPath, "utf8"));
const expiryDate = new Date(tokens.expiry_date);
const now = new Date();
const isExpired = now > expiryDate;
const hasRefreshToken = !!tokens.refresh_token;

console.log("Token Status Report");
console.log("===================");
console.log("Access token expires:", expiryDate.toISOString());
console.log("Current time:", now.toISOString());
console.log("Access token status:", isExpired ? "EXPIRED" : "VALID");
console.log("Refresh token present:", hasRefreshToken ? "YES" : "NO");

if (isExpired && hasRefreshToken) {
  console.log("\nNote: Access token is expired but will auto-refresh on next API call.");
}

if (isExpired && !hasRefreshToken) {
  console.log("\nWARNING: Access token expired and no refresh token available.");
  console.log("Re-run authorization flow to get new tokens.");
}
EOF
```

---

## Re-Authorization Flow {#reauthorize}

When refresh tokens are invalid, run the full authorization flow again:

```bash
# Remove old tokens and re-authorize
rm ~/.gmail-skill/tokens.json

# Then run the authorization script from Step 5
```

---

## Troubleshooting {#troubleshooting}

### Error: "invalid_grant"

**Symptoms**:
```
Error: invalid_grant
```

**Causes**:
1. Authorization code already used (codes are single-use)
2. Authorization code expired (valid for ~10 minutes)
3. Refresh token revoked or expired
4. Clock skew between your machine and Google servers

**Solutions**:
```bash
# Remove tokens and re-authorize
rm ~/.gmail-skill/tokens.json
# Run authorization flow again
```

### Error: "Access blocked: This app's request is invalid"

**Symptoms**:
OAuth consent screen shows "Access blocked" error

**Causes**:
1. Redirect URI mismatch
2. App not published and user not in test users list

**Solutions**:
1. Verify redirect URI in Cloud Console matches `client_secret.json`
2. Add your email to test users (OAuth consent screen > Test users)

### Error: "redirect_uri_mismatch"

**Symptoms**:
```
Error 400: redirect_uri_mismatch
```

**Causes**:
Redirect URI in authorization request doesn't match registered URIs

**Solutions**:
1. Go to Cloud Console > Credentials > Your OAuth client
2. Add `http://localhost` to Authorized redirect URIs
3. Download new `client_secret.json`

### Error: "deleted_client"

**Symptoms**:
```
Error: The OAuth client was deleted
```

**Causes**:
OAuth client credentials were deleted from Cloud Console

**Solutions**:
1. Create new OAuth client in Cloud Console
2. Download new `client_secret.json`
3. Remove old `tokens.json` and re-authorize

### Error: "Token has been expired or revoked"

**Symptoms**:
```
Error: Token has been expired or revoked
```

**Causes**:
1. Refresh token expired (testing app > 7 days)
2. User revoked access in Google Account settings
3. Password changed

**Solutions**:
```bash
rm ~/.gmail-skill/tokens.json
# Re-run authorization flow
```

### Error: "Insufficient Permission"

**Symptoms**:
```
Error 403: Insufficient Permission
```

**Causes**:
Requested operation requires scopes not granted during authorization

**Solutions**:
1. Check which scopes your app has
2. Add required scopes in OAuth consent screen
3. Remove `tokens.json` and re-authorize with correct scopes

```bash
# View currently authorized scopes
tsx << 'EOF'
import { readFileSync } from "fs";
import { homedir } from "os";
import { join } from "path";

const tokens = JSON.parse(readFileSync(join(homedir(), ".gmail-skill/tokens.json"), "utf8"));
console.log("Authorized scopes:", tokens.scope);
EOF
```

### Error: "Quota exceeded"

**Symptoms**:
```
Error 429: Quota exceeded for quota metric
```

**Causes**:
Hit Gmail API rate limits (250 quota units/user/second)

**Solutions**:
1. Implement exponential backoff
2. Use batch operations
3. Request quota increase in Cloud Console

### Testing App Token Expiry

If your app is in "Testing" status, refresh tokens expire after 7 days.

**Check publishing status**:
1. Go to Cloud Console > APIs & Services > OAuth consent screen
2. Check "Publishing status" section

**Solutions**:
1. **For development**: Re-authorize every 7 days
2. **For production**: Click "Publish App" and complete verification

---

## Security Best Practices {#security}

### Protect Credential Files

```bash
# Set restrictive permissions
chmod 600 ~/.gmail-skill/client_secret.json
chmod 600 ~/.gmail-skill/tokens.json

# Verify permissions
ls -la ~/.gmail-skill/
# Should show: -rw-------
```

### Never Commit Credentials

Add to `.gitignore`:
```
.gmail-skill/
client_secret.json
tokens.json
```

### Rotate Credentials If Exposed

If `client_secret.json` is exposed:
1. Go to Cloud Console > Credentials
2. Delete compromised OAuth client
3. Create new OAuth client
4. Download new `client_secret.json`
5. Re-authorize

If `tokens.json` is exposed:
1. Go to [Google Account Security](https://myaccount.google.com/permissions)
2. Find and remove the app
3. Delete `tokens.json`
4. Re-authorize

---

## OAuth Scopes Reference {#scopes}

Choose the minimum scopes required for your operations:

| Scope | Permissions | Operations |
|-------|-------------|------------|
| `gmail.readonly` | Read-only access | List, get messages/threads/labels |
| `gmail.compose` | Create drafts | Create, update, delete drafts |
| `gmail.send` | Send emails | Send messages and drafts |
| `gmail.modify` | Full access | All read/write operations (recommended) |
| `gmail.labels` | Labels only | Create, update, delete labels |
| `gmail.settings.basic` | Basic settings | Vacation responder, auto-forwarding |

### Scope Combinations

| Use Case | Scopes Needed |
|----------|---------------|
| Read emails only | `gmail.readonly` |
| Send emails only | `gmail.send` |
| Read and send | `gmail.readonly` + `gmail.send` |
| Full email management | `gmail.modify` |
| Settings management | `gmail.modify` + `gmail.settings.basic` |

### Requesting Multiple Scopes

Modify the SCOPES array in the authorization script:

```typescript
const SCOPES = [
  "https://www.googleapis.com/auth/gmail.modify",
  "https://www.googleapis.com/auth/gmail.settings.basic"
];
```

---

## Quick Verification Script {#verify}

After setup, verify everything works:

```bash
tsx << 'EOF'
import { google } from "googleapis";
import { readFileSync, writeFileSync, existsSync } from "fs";
import { homedir } from "os";
import { join } from "path";

const credPath = join(homedir(), ".gmail-skill");
const clientSecretPath = join(credPath, "client_secret.json");
const tokensPath = join(credPath, "tokens.json");

console.log("=== Gmail OAuth Verification ===\n");

// Check files
const checks = [
  { name: "Credential directory", path: credPath },
  { name: "Client secret", path: clientSecretPath },
  { name: "Tokens", path: tokensPath }
];

let allPassed = true;
for (const check of checks) {
  const exists = existsSync(check.path);
  console.log(`${exists ? "[OK]" : "[FAIL]"} ${check.name}: ${check.path}`);
  if (!exists) allPassed = false;
}

if (!allPassed) {
  console.log("\nSetup incomplete. See sections above for missing components.");
  process.exit(1);
}

// Test connection
try {
  const credentials = JSON.parse(readFileSync(clientSecretPath, "utf8"));
  const tokens = JSON.parse(readFileSync(tokensPath, "utf8"));

  const oauth2Client = new google.auth.OAuth2(
    credentials.installed.client_id,
    credentials.installed.client_secret,
    credentials.installed.redirect_uris[0]
  );
  oauth2Client.setCredentials(tokens);
  oauth2Client.on("tokens", (newTokens) => {
    const updated = { ...tokens, ...newTokens };
    writeFileSync(tokensPath, JSON.stringify(updated, null, 2));
  });

  const gmail = google.gmail({ version: "v1", auth: oauth2Client });
  const profile = await gmail.users.getProfile({ userId: "me" });

  console.log("\n[OK] API connection successful");
  console.log("    Email:", profile.data.emailAddress);
  console.log("    Total messages:", profile.data.messagesTotal);
  console.log("    Total threads:", profile.data.threadsTotal);

  // Check scopes
  console.log("\n[OK] Authorized scopes:");
  const scopes = tokens.scope?.split(" ") || [];
  for (const scope of scopes) {
    console.log("    -", scope.replace("https://www.googleapis.com/auth/", ""));
  }

  console.log("\n=== All checks passed ===");

} catch (error: any) {
  console.log("\n[FAIL] API connection failed:", error.message);

  if (error.code === 401) {
    console.log("\nYour tokens may be expired or revoked.");
    console.log("Delete tokens.json and re-authorize.");
  }

  process.exit(1);
}
EOF
```
