#!/usr/bin/env bash

YELLOW='\033[1;33m'
GREEN='\033[1;32m'
NC='\033[0m'

BRANCH_NAME=$(git branch | grep "*" | sed "s/\* //")
ENV_FILE_NAME=./environment/.env.branch.$(echo $BRANCH_NAME | sed -e "s/\//\./g")
MERGED_BRANCH_NAME=$(git reflog | grep ": merge" | head -n 1 | cut -d" " -f 4 | sed "s/://")
MERGED_ENV_FILE_NAME=./environment/.env.branch.$(echo $MERGED_BRANCH_NAME | sed -e "s/\//\./g")

if [[ ! -f "$ENV_FILE_NAME" ]]
then
  # If the branch environment file does not exist, 
  # create and link to .env.branch then exit with an error
  touch $ENV_FILE_NAME
  git add $ENV_FILE_NAME
  ln -nsf $ENV_FILE_NAME .env.branch
  git add .env.branch
  printf "\n******\n\n${YELLOW}${ENV_FILE_NAME} did not exist!\n\nThe file was created and the .env.branch symlink was updated.\n\nPlease review and commit the changes.${NC}\n\n******\n\n"
  exit 1
fi

if [[ "$BRANCH_NAME" == "$MERGED_BRANCH_NAME" ]]
then
  if [[ "$(realpath .env.branch)" == "$(realpath $ENV_FILE_NAME)" ]]
  then
    # If the branch names are the same and .env.branch is properly
    # linked, exit with success
    exit 0
  fi
  # If the .env.branch link is pointing to the wrong file, update
  # the link, commit changes and exit
  ln -nsf $ENV_FILE_NAME .env.branch
  git add .env.branch
  printf "\n******\n\n${GREEN}The .env.branch symlink did not point to ${ENV_FILE_NAME}.\n\nThe symlink was updated and the changes were committed.${NC}\n\n******\n\n"
  git commit -m "Update .env.branch symbolic link in $BRANCH_NAME"
  exit 0
fi

ENV_FILE_NAME_EXISTS_IN_MERGED_BRANCH=$(git cat-file -e $MERGED_BRANCH_NAME:$ENV_FILE_NAME 2> /dev/null && echo "TRUE" || echo "FALSE")

if [[ $ENV_FILE_NAME_EXISTS_IN_MERGED_BRANCH == "FALSE" ]]
then
  # The merged branch does not contain the environment variable file.
  # We are merging an upstream.
  exit 0
fi

# Remove the merged branch environment file if it exists
if [[ -f "$MERGED_ENV_FILE_NAME" ]]
then
  git rm $MERGED_ENV_FILE_NAME 2> /dev/null || true
fi

# Link the branch environment file to .env.branch
ln -nsf $ENV_FILE_NAME .env.branch
git add .env.branch

printf "\n******\n\n${GREEN}${MERGED_ENV_FILE_NAME} was removed, the .env.branch symlink was updated to point to ${ENV_FILE_NAME}, and the changes were committed.${NC}\n\n******\n\n"
git commit -m "Remove environment variable file from $MERGED_BRANCH_NAME in $BRANCH_NAME"
