#!/usr/bin/env bash

YELLOW='\033[1;33m'
GREEN='\033[1;32m'
NC='\033[0m'

NEW_BRANCH_NAME=`git reflog | grep checkout: | awk 'NR==1{ print $8; exit }'`
NEW_ENV_FILE_NAME=./environment/.env.branch.$(echo $NEW_BRANCH_NAME | sed -e "s/\//\./g")

if [[ -f "$NEW_ENV_FILE_NAME" && -f ".env.branch" && "$(realpath .env.branch)" == "$(realpath $NEW_ENV_FILE_NAME)" ]]
then
  # If the new branch environment file exists and is properly linked, exit with success
  exit 0
fi

OLD_BRANCH_NAME=`git reflog | grep checkout: | awk 'NR==1{ print $6; exit }'`
OLD_ENV_FILE_NAME=./environment/.env.branch.$(echo $OLD_BRANCH_NAME | sed -e "s/\//\./g")

if [[ -f "$NEW_ENV_FILE_NAME" ]]
then
  ln -nsf $NEW_ENV_FILE_NAME .env.branch
  git add .env.branch
  printf "\n******\n\n${GREEN}Updated .env.branch symlink to point to ${NEW_ENV_FILE_NAME} and committed changes.${NC}\n\n******\n\n"
  git commit -m "Updated .env.branch symlink to point to ${NEW_ENV_FILE_NAME}"
  exit 0;
fi

if [[ ! -f "$OLD_ENV_FILE_NAME" ]]
then
  # If the old branch environment does not exist, create and link the new files then exit with an error
  touch $NEW_ENV_FILE_NAME
  git add $NEW_ENV_FILE_NAME
  ln -nsf $NEW_ENV_FILE_NAME .env.branch
  git add .env.branch
  printf "\n******\n\n${YELLOW}${OLD_ENV_FILE_NAME} did not exist!\n\nCreated an empty ${NEW_ENV_FILE_NAME} file and updated .env.branch symlink. Please review the ${NEW_ENV_FILE_NAME} file and commit your changes.${NC}\n\n******\n\n"
  exit 1
fi

# Copy the old branch environment file to the new branch environment file, link, and commit
cp $OLD_ENV_FILE_NAME $NEW_ENV_FILE_NAME
git add $NEW_ENV_FILE_NAME
ln -nsf $NEW_ENV_FILE_NAME .env.branch
git add .env.branch
printf "\n******\n\n${GREEN}Copied ${OLD_ENV_FILE_NAME} to ${NEW_ENV_FILE_NAME}, updated .env.branch symlink, and committed changes.${NC}\n\n******\n\n"
git commit -m "Copied ${OLD_ENV_FILE_NAME} to ${NEW_ENV_FILE_NAME} and updated .env.branch symlink"


