cacheFolder: ./.yarn/shared-cache

globalFolder: ./.yarn/shared-global

installStatePath: ./.yarn/install-state.gz

nodeLinker: node-modules

plugins:
  - checksum: 9b5a0634c914c9e3ec1b95d8faa828ff48c5718121b696aaa9da219726fba41ec0aa229cc77509b82cfc2352746e21150a7a37b9e868f5041f6509a840cefb61
    path: .yarn/plugins/@yarnpkg/plugin-worktree-isolation.cjs
    spec: packages/yarn-plugin-worktree-isolation/bundles/@yarnpkg/plugin-worktree-isolation.js
